# Generated by Django 5.1.7 on 2025-03-07 00:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apps1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apps2",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apps3",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apps4",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apps5",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apps6",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apps7",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaConsolidada1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaConsolidada2",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaImovel1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField()),
                ("nom_tema", models.TextField()),
                ("mod_fiscal", models.FloatField()),
                ("num_area", models.FloatField()),
                ("ind_status", models.TextField()),
                ("ind_tipo", models.TextField()),
                ("des_condic", models.TextField()),
                ("municipio", models.TextField()),
                ("cod_estado", models.TextField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaPousio1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hidrografia1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservaLegal1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServidaoAdministrativa1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=100, unique=True)),
                ("is_running", models.BooleanField(default=False)),
                (
                    "last_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_started", models.DateTimeField(blank=True, null=True)),
                ("last_finished", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("next_schedule", models.DateTimeField(blank=True, null=True)),
                (
                    "time_next_schedule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsoRestrito1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VegetacaoNativa1",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VegetacaoNativa2",
            fields=[
                (
                    "gid",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("cod_imovel", models.CharField(max_length=255)),
                ("cod_tema", models.TextField(null=True)),
                ("nom_tema", models.TextField(null=True)),
                ("num_area", models.FloatField(null=True)),
                ("ind_status", models.TextField(null=True)),
                ("des_condic", models.TextField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4674),
                ),
            ],
        ),
    ]
