# Generated by Django 5.1.7 on 2025-03-07 00:26

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supressao_apos_2008", models.CharField(max_length=255)),
                ("tipo_area", models.CharField(max_length=255)),
                ("tamanho_imovel", models.CharField(max_length=255)),
                ("potencial_regeneracao_natural", models.CharField(max_length=255)),
                ("dinamica_hidrica", models.CharField(max_length=255)),
                ("pedregosidade_solo", models.CharField(max_length=255)),
                ("estrutura_ecossistema", models.CharField(max_length=255)),
                ("condicoes_solo", models.CharField(max_length=255)),
                ("ocupacao_area", models.CharField(max_length=255)),
                ("declividade", models.CharField(max_length=255)),
                (
                    "fatores_perturbacao",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4674),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bioma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fid", models.IntegerField(verbose_name="FID")),
                ("bioma", models.CharField(max_length=255, verbose_name="Bioma")),
                (
                    "bioma_name",
                    models.CharField(max_length=255, verbose_name="Nome do Bioma"),
                ),
                ("bioma_code", models.IntegerField(verbose_name="Código do Bioma")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4674, verbose_name="Geometria"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["geometry"],
                        name="bioma_geometry_idx",
                        opclasses=["gist"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bioma", models.CharField(max_length=255, verbose_name="Bioma")),
                (
                    "bioma_name",
                    models.CharField(max_length=255, verbose_name="Nome do Bioma"),
                ),
                (
                    "nome_cientifico",
                    models.CharField(max_length=255, verbose_name="Nome Científico"),
                ),
                ("codigo", models.IntegerField(verbose_name="Código")),
                ("habito", models.CharField(max_length=255, verbose_name="Hábito")),
                ("distribuicao", models.TextField(verbose_name="Distribuição")),
                (
                    "subdominio_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        size=None,
                        verbose_name="Lista de Subdomínios",
                    ),
                ),
                ("fisionomias", models.TextField(verbose_name="Fisionomias")),
                (
                    "conservacao",
                    models.CharField(max_length=255, verbose_name="Conservação"),
                ),
                ("nomes_populares", models.TextField(verbose_name="Nomes Populares")),
                (
                    "categorias_ecofisiologicas",
                    models.CharField(
                        max_length=255, verbose_name="Categorias Ecofisiológicas"
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["subdominio_list"],
                        name="projeto_esp_subdomi_cf5785_gin",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subdominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fid", models.IntegerField(verbose_name="FID")),
                ("bioma", models.CharField(max_length=255, verbose_name="Bioma")),
                (
                    "subdominio",
                    models.CharField(max_length=255, verbose_name="Subdomínio"),
                ),
                (
                    "subdominio_code",
                    models.IntegerField(verbose_name="Subdomínio Code"),
                ),
                (
                    "bioma_name",
                    models.CharField(max_length=255, verbose_name="Nome do Bioma"),
                ),
                ("bioma_code", models.IntegerField(verbose_name="Código do Bioma")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4674, verbose_name="Geometria"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["geometry"],
                        name="subdominio_geometry_idx",
                        opclasses=["gist"],
                    )
                ],
            },
        ),
    ]
